### ISSUE TITLE
Removal links are unreachable

### ISSUE THREAD

**Issue by KoenPasman** [haubek/bootstrap4c-dropzone#1]
When using removal links (using the `addRemovalLinks` option), the link gets added, but is not reachable due to `.dz-details` having `height:100%`. 

Running Bootstrap v4.0.0-alpha6

![image](https://user-images.githubusercontent.com/1674580/28324822-9cdec042-6bdc-11e7-92a9-80c353cd6fbf.png)

**Comment by haubek** [comment]
Thanks @KoenPasman -- I'll look into this asap.
